# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userPhone', models.CharField(max_length=15)),
                ('userEmail', models.CharField(max_length=100)),
                ('isVail', models.BooleanField(default=True)),
                ('pwd', models.CharField(max_length=100)),
                ('valCode', models.CharField(max_length=10)),
            ],
        ),
    ]
