# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20180402_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='validcode',
            name='accesstoken',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
