# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_validcode_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accesstoken',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
