# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_user_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accesstoken',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
