# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20180418_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validcode',
            name='accesstoken',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
